# Docker Compose konfigurace pro MongoDB sharded cluster s Jupyter notebookem a seederem
# Tento soubor definuje všechny služby potřebné pro běh MongoDB clusteru s více shardy, konfiguračními servery a dvěma routery.
# Součástí je také seeder pro naplnění databáze.

services:
  # Seeder slouží pro inicializaci.
  # Kontejner pouze čeká (sleep infinity) naruční spouštění skriptů.
  # Připojené volume umožňují přístup ke skriptům a datům z hostitelského systému.
  seeder:
    build:
      context: .
      dockerfile: seeder.Dockerfile
    volumes:
      - ./scripts:/scripts      # Skripty pro seedování dat
      - ./dataset:/dataset      # Datové soubory pro import
    entrypoint: ["sleep", "infinity"]

## Router
  # Mongos routery pro směrování dotazů do clusteru.
  # Tyto služby zajišťují, že klientské aplikace komunikují s clusterem přes jednotné rozhraní.
  # Každý router je připojen ke všem konfiguračním serverům a používá sdílený klíč pro autentizaci.
  router01:
    build: 
      context: docker
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all --keyFile /data/mongodb-keyfile
    ports:
      - 27117:27017             # Mapování portu pro přístup k routeru
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_router01_db:/data/db           # Perzistence dat routeru
      - mongodb_cluster_router01_config:/data/configdb # Perzistence konfigurace routeru
  router02:
    build: 
      context: docker
    container_name: router-02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_router02_db:/data/db
      - mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    links:
      - router01                # Propojení mezi routery pro případné závislosti

## Config Servers
  # Konfigurační servery pro uchování metadat clusteru.
  # Tyto servery uchovávají informace o rozložení dat a konfiguraci shardů.
  # Každý konfigurační server je součástí replikačního setu rs-config-server.
  configsvr01:
    build: 
      context: docker
    container_name: mongo-config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts 
      - ./dataset:/dataset
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    links:
      - shard01-a    # Propojení na primární nody jednotlivých shardů
      - shard02-a
      - shard03-a
      - configsvr02  # Propojení na ostatní konfigurační servery
      - configsvr03
  configsvr02:
    build: 
      context: docker
    container_name: mongo-config-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_configsvr02_db:/data/db
      - mongodb_cluster_configsvr02_config:/data/configdb
    ports:
      - 27120:27017
    restart: always
  configsvr03:
    build: 
      context: docker
    container_name: mongo-config-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_configsvr03_db:/data/db
      - mongodb_cluster_configsvr03_config:/data/configdb
    ports:
      - 27121:27017
    restart: always

## Shards
  ## Shards 01
  # Každý shard je replikovaný přes tři nody (a, b, c) pro vysokou dostupnost.
  # Shard 01 - replikační set rs-shard-01
  shard01-a:
    build: 
      context: docker 
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27122:27017
    restart: always
    links:
      - shard01-b   # Propojení na ostatní nody v rámci shardu
      - shard01-c
  shard01-b:
    build: 
      context: docker
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard01_b_db:/data/db
      - mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always
  shard01-c:
    build: 
      context: docker
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard01_c_db:/data/db
      - mongodb_cluster_shard01_c_config:/data/configdb
    ports:
      - 27124:27017
    restart: always

  ## Shards 02
  # Shard 02 - replikační set rs-shard-02
  shard02-a:
    build: 
      context: docker
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    build: 
      context: docker
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard02_b_db:/data/db
      - mongodb_cluster_shard02_b_config:/data/configdb
    ports:
      - 27126:27017
    restart: always
  shard02-c:
    build: 
      context: docker
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard02_c_db:/data/db
      - mongodb_cluster_shard02_c_config:/data/configdb
    ports:
      - 27127:27017
    restart: always

  ## Shards 03
  # Shard 03 - replikační set rs-shard-03
  shard03-a:
    build: 
      context: docker
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard03_a_db:/data/db
      - mongodb_cluster_shard03_a_config:/data/configdb
    ports:
      - 27128:27017
    restart: always
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    build: 
      context: docker
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard03_b_db:/data/db
      - mongodb_cluster_shard03_b_config:/data/configdb
    ports:
      - 27129:27017
    restart: always
  shard03-c:
    build: 
      context: docker
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03 --keyFile /data/mongodb-keyfile
    volumes:
      - ./scripts:/scripts
      - ./dataset:/dataset
      - mongodb_cluster_shard03_c_db:/data/db
      - mongodb_cluster_shard03_c_config:/data/configdb
    ports:
      - 27130:27017
    restart: always

# Definice pojmenovaných Docker volume pro perzistenci dat jednotlivých služeb.
volumes:
  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:
  
  mongodb_cluster_router02_db:
  mongodb_cluster_router02_config:
  
  mongodb_cluster_configsvr01_db:
  mongodb_cluster_configsvr01_config:
  
  mongodb_cluster_configsvr02_db:
  mongodb_cluster_configsvr02_config:
  
  mongodb_cluster_configsvr03_db:
  mongodb_cluster_configsvr03_config:
  
  mongodb_cluster_shard01_a_db:
  mongodb_cluster_shard01_a_config:
  
  mongodb_cluster_shard01_b_db:
  mongodb_cluster_shard01_b_config:
  
  mongodb_cluster_shard01_c_db:
  mongodb_cluster_shard01_c_config:
  
  mongodb_cluster_shard02_a_db:
  mongodb_cluster_shard02_a_config:
  
  mongodb_cluster_shard02_b_db:
  mongodb_cluster_shard02_b_config:
  
  mongodb_cluster_shard02_c_db:
  mongodb_cluster_shard02_c_config:
  
  mongodb_cluster_shard03_a_db:
  mongodb_cluster_shard03_a_config:
  
  mongodb_cluster_shard03_b_db:
  mongodb_cluster_shard03_b_config:
  
  mongodb_cluster_shard03_c_db:
  mongodb_cluster_shard03_c_config:
